### ISSUE TITLE
Zero mAP on validation.

### ISSUE THREAD

**Issue by lysukhin** [ammirato/target_driven_instance_detection#1]
Hello!

I'm trying to reproduce your results by running `train_tdid.py`.
All of necessary data seem to be in place. All of config parameters are set to default (except for model saving frequency which is set to 1 along with saving by epoch which is set to `True`).

After 7 epochs the validation mAP is exactly 0. `ls` on `Models` output dir shows the following contents:
```
TDID_AVD2_01_1_1798_16.98650_0.00000.h5
TDID_AVD2_01_2_3595_9.54894_0.00000.h5
TDID_AVD2_01_3_5392_7.26019_0.00000.h5
TDID_AVD2_01_4_7189_5.52172_0.00000.h5
TDID_AVD2_01_5_8986_4.31714_0.00000.h5
TDID_AVD2_01_6_10783_4.04481_0.00000.h5
TDID_AVD2_01_7_12580_3.55785_0.00000.h5
```

Do you have the idea of what may be wrong with it? How many epochs are required for a sensible result? What are the good places to start debugging?

Thanks in advance.

**Comment by pammirato** [comment]
Hi, sorry the the late reply, I didn't have email notifications turned on. I should be more responsive in the future. 

You should see results above 0 on the first or second epoch. It's good that the training error is going down though. 

Probably it is that the boxes outputted from the testing function are not scaled properly for the ground truth boxes. i.e. during testing the images are halved in each dimension and so are the bounding boxes, but the ground truth boxes are for the full image size. **I think this is fixed in the latest update**.

I would start by retrying with the updated code, and if there is still a problem, try to visualize some of the outputted boxes from the model, and make the target images are being loaded correctly. 

We have also uploaded some trained models, so you can see if you can get those to work with testing and evaluation code.

**Comment by ammirato** [comment]
Hi, sorry the the late reply, I didn't have email notifications turned on. I should be more responsive in the future.

You should see results above 0 on the first or second epoch. It's good that the training error is going down though.

Probably it is that the boxes outputted from the testing function are not scaled properly for the ground truth boxes. i.e. during testing the images are halved in each dimension and so are the bounding boxes, but the ground truth boxes are for the full image size. I think this is fixed in the latest update.

I would start by retrying with the updated code, and if there is still a problem, try to visualize some of the outputted boxes from the model, and make the target images are being loaded correctly.

We have also uploaded some trained models, so you can see if you can get those to work with testing and evaluation code.

**Comment by lysukhin** [comment]
Hi, @ammirato!

Thanks for your reply. I will try to test the update and return to you as soon as I get results.
