### ISSUE TITLE
Target Image 

### ISSUE THREAD

**Issue by LegaDyan** [ammirato/target_driven_instance_detection#3]
Excuse me, would you please kindly tell me what target images you are using in training and testing when you work on section C "Few Shot Instance Detection"'s _RGB-D Scene_ and _GMU Kitchens_ experiment?

**Comment by ammirato** [comment]
First I should note it sounds like you have an older version of the paper, see [here](https://arxiv.org/pdf/1803.04610.pdf) for an updated version.

For target images, we look in three places in this order:
    1. the Target Images given on the AVD website
    2. crops of the objects from the BigBIRD dataset
    3. the classification style images from RGB-D Objects

We always attempt to choose target images so that we have a good view of the back and front of the object. We usually use two target images. 

[Here is an example](https://drive.google.com/file/d/1QM4PMQVL5rvLjwwqcDFHgy1VJcsg-jsc/view?usp=sharing).

**Comment by LegaDyan** [comment]
Thank you so much!

There's one more question: according to the updated paper, the details about the **_4.3 Few Shot Instance Detection_** can be found in the appendix. However, there's no appendix after the paper... 😭

**Comment by ammirato** [comment]
No problem!

Haha yes sorry I forgot arxiv is slow. I **updated the link** in my comment above to the full version on my webpage
